#Cau hinh dia chi FTP Server
#Sat Aug 01 00:43:55 GMT+07:00 2026
db.password=danh
db.url=jdbc\:mysql\://localhost\:3306/file_transfer_app?useSSL\=false&serverTimezone\=UTC&allowPublicKeyRetrieval\=true
db.user=root
server_ip=127.0.0.1
server_port=5000
